#!/bin/bash

# display subdomain information
display_subdomain_info() {
    subdomain=$1
    domain=$2
    record_type=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION/ {getline; print $4}')
    end_result=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${end_result}"
}

# main
if [ $# -eq 0 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1

# to check if subdomain is provided, else use default subdomains
if [ $# -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$2")
fi

for subdomain in "${subdomains[@]}"; do
    display_subdomain_info "${subdomain}" "${domain}"
done
