#!/usr/bin/env bash
# Installs Nginx on webserver web-01
# update and install
sudo apt-get update
sudo apt-get install -y nginx

# createa index.html page
echo "Hello World!" > /var/www/html/index.html

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx
sudo service nginx restart
