#!/usr/bin/env bash
# redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World" | sudo tee /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/PatriciaMkoji permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
