#!/usr/bin/env bash
#redirection of web page

# update and installl
sudo apt-get update
sudo apt-get install -y nginx

# createa index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# permanent redirection-301
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/PatriciaMkoji permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx
sudo service nginx restart
