#!/usr/bin/env bash
# redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=zuS9T3yXPWo permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

sudo service nginx restart
