#!/usr/bin/env bash
# configure your Nginx server to have a custom 404 page

# update and install
sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# createa index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# permanent redirection-301
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/PatriciaMkoji permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# create error an error page and redirect for 404 error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/github.com\/PatriciaMkoji.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default


# Testing configurations for syntax errors
sudo nginx -t

# restart nginx
sudo service nginx restart
