#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# install & config HAproxy
sudo apt-get -y update
sudo apt-get -y istall haproxy

