#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

function leave() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;leave" SIGTERM
trap "echo Y U no love me?!;leave" SIGINT

echo $$ >> /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
done
