#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
# script should only display username, user id, Home directory path
while IFS=: read -r file
do
	echo "$file" | cut -d ":" -f 1,3,6
done < /etc/passwd
