#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best# School and then Hi on a new line.
i=0
while [ $i -le 9 ];
do
	if [ $i -eq  9 ];
	then
		echo "HI"
	fi
	
	echo "Best School"
	((i++))
done
