#!/usr/bin/env bash
# loops from 1 to 10 and displays bad luck for the 4th loop iteration
# displays good luck for8th loop & Best School for the other iterations
i=0
while [ $i -le 9 ];
do
	if [ $i -eq 3 ];
	then
		echo "bad luck"
	elif [ $i -eq 7 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
