#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12 & display minutes from 1 to 59
i=0
while [ $i -lt 13 ];
do
  echo "Hour: $i"
  (( i++ ))
  h=1
    while [ $h -lt 60 ]
    do
      echo "$h"
      (( h++ ))
    done
done
