#!/usr/bin/env bash
# displays content of the current directory & In a list format
# Where only the part of the name after the first dash is displayed
for search in *
do
	echo "$search" | cut -d "-" -f 2
done
