#!/usr/bin/env bash
# configures localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8.
echo "127.0.0.1 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
